[package]
name = "fisherman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.37.1"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"